- name: Windows | Firewall rules to allow inbound traffic
  hosts: windows
  community.windows.win_firewall_rule:
    name: HTTPS
    localport: 8443
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
