---
- name: "Create the ES DNS record"
  hosts: dcs
  tasks:
    - name: "Crerate A record"
      community.windows.win_dns_record:
         name: "testserver"
         type: "A"
         value: "172.16.10.8"
         zone: "es.vipnet.local"
