---
- name: "Join Domain"
  hosts: windows
  tasks:
    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: vipnet.local
        hostname: cl01
        domain_admin_user: administrator@vipnet.local
        domain_admin_password: vbdf123@VP
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required
